// Generated by CoffeeScript 1.6.3
(function() {
  var app, express,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  express = require("express");

  app = express();

  app.use(function(req, res) {
    var rootHosts, _ref;
    rootHosts = ["localhost:3141"];
    if (_ref = req.headers.host, __indexOf.call(rootHosts, _ref) >= 0) {
      return res.send("You are at root");
    } else {
      return res.send("You are at a subdomain: " + req.headers.host.split(".")[0]);
    }
  });

  console.log("App started on http://localhost:3141");

  app.listen(3141);

}).call(this);
